import { useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';

export interface FinancialTransaction {
  id: string;
  order_id: string | null;
  type: 'income' | 'expense' | 'refund';
  category: string;
  amount: number;
  description: string | null;
  payment_method: string | null;
  reference_number: string | null;
  created_at: string;
  created_by: string | null;
}

export interface Invoice {
  id: string;
  invoice_number: string;
  order_id: string | null;
  customer_name: string | null;
  customer_email: string | null;
  customer_phone: string | null;
  subtotal: number;
  tax_amount: number;
  discount_amount: number;
  total_amount: number;
  status: 'pending' | 'paid' | 'cancelled' | 'refunded';
  due_date: string | null;
  paid_at: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface Expense {
  id: string;
  category: string;
  amount: number;
  description: string | null;
  vendor: string | null;
  receipt_url: string | null;
  expense_date: string;
  created_at: string;
  created_by: string | null;
}

// Default page size keeps queries well under Supabase's 1000-row cap.
const PAGE_LIMIT = 500;

export const useFinancialTransactions = () => {
  return useQuery({
    queryKey: ['financial-transactions'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('financial_transactions')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(PAGE_LIMIT);
      if (error) throw error;
      return data as FinancialTransaction[];
    },
  });
};

export const useInvoices = () => {
  return useQuery({
    queryKey: ['invoices'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('invoices')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(PAGE_LIMIT);
      if (error) throw error;
      return data as Invoice[];
    },
  });
};

export const useExpenses = () => {
  return useQuery({
    queryKey: ['expenses'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('expenses')
        .select('*')
        .order('expense_date', { ascending: false })
        .limit(PAGE_LIMIT);
      if (error) throw error;
      return data as Expense[];
    },
  });
};

export const useCreateTransaction = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: Omit<FinancialTransaction, 'id' | 'created_at'>) => {
      const { error } = await supabase.from('financial_transactions').insert(data);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['financial-transactions'] });
    },
  });
};

export const useUpdateTransaction = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, ...data }: Partial<FinancialTransaction> & { id: string }) => {
      const { error } = await supabase.from('financial_transactions').update(data).eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['financial-transactions'] });
    },
  });
};

export const useDeleteTransaction = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('financial_transactions').delete().eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['financial-transactions'] });
    },
  });
};

export const useCreateInvoice = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: Omit<Invoice, 'id' | 'invoice_number' | 'created_at' | 'updated_at'>) => {
      const { error } = await supabase.from('invoices').insert({
        invoice_number: '', // Will be auto-generated by trigger
        order_id: data.order_id,
        customer_name: data.customer_name,
        customer_email: data.customer_email,
        customer_phone: data.customer_phone,
        subtotal: data.subtotal,
        tax_amount: data.tax_amount,
        discount_amount: data.discount_amount,
        total_amount: data.total_amount,
        status: data.status,
        due_date: data.due_date,
        paid_at: data.paid_at,
        notes: data.notes,
      });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
    },
  });
};

export const useUpdateInvoice = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, ...data }: Partial<Invoice> & { id: string }) => {
      const { error } = await supabase.from('invoices').update(data).eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
    },
  });
};

export const useDeleteInvoice = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('invoices').delete().eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
    },
  });
};

export const useCreateExpense = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: Omit<Expense, 'id' | 'created_at'>) => {
      const { data: expense, error } = await supabase.from('expenses').insert(data).select().single();
      if (error) throw error;
      
      // Also create a financial transaction for the expense
      await supabase.from('financial_transactions').insert({
        type: 'expense',
        category: data.category,
        amount: data.amount,
        description: data.description,
        created_by: data.created_by,
      });
      
      return expense;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['expenses'] });
      queryClient.invalidateQueries({ queryKey: ['financial-transactions'] });
    },
  });
};

export const useDeleteExpense = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('expenses').delete().eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['expenses'] });
    },
  });
};

// Financial summary calculations - excludes cancelled orders, counts paid revenue up-to-date
export const useFinancialSummary = () => {
  const queryClient = useQueryClient();
  const { data: invoices } = useInvoices();
  const { data: expenses } = useExpenses();
  const { data: orders } = useQuery({
    queryKey: ['orders-summary'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select('total_amount, status, created_at, payment_status')
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data;
    },
    refetchInterval: 15000, // poll every 15s as a safety net
  });

  // Realtime: refresh whenever orders/transactions change
  useEffect(() => {
    const channel = supabase
      .channel('finance-summary-realtime')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'orders' }, () => {
        queryClient.invalidateQueries({ queryKey: ['orders-summary'] });
      })
      .on('postgres_changes', { event: '*', schema: 'public', table: 'financial_transactions' }, () => {
        queryClient.invalidateQueries({ queryKey: ['financial-transactions'] });
        queryClient.invalidateQueries({ queryKey: ['orders-summary'] });
      })
      .on('postgres_changes', { event: '*', schema: 'public', table: 'expenses' }, () => {
        queryClient.invalidateQueries({ queryKey: ['expenses'] });
      })
      .on('postgres_changes', { event: '*', schema: 'public', table: 'invoices' }, () => {
        queryClient.invalidateQueries({ queryKey: ['invoices'] });
      })
      .subscribe();
    return () => { supabase.removeChannel(channel); };
  }, [queryClient]);

  // Exclude cancelled orders entirely. Revenue = any PAID order that isn't cancelled.
  const validOrders = orders?.filter(o => o.status !== 'cancelled') || [];
  const paidOrders = validOrders.filter(o => o.payment_status === 'paid');
  const deliveredOrders = validOrders.filter(o => o.status === 'delivered');

  const grossRevenue = paidOrders.reduce((sum, o) => sum + Number(o.total_amount), 0);
  // Subtract any refunds recorded in financial_transactions (e.g. cancelled-after-paid orders)
  const refundsTotal = useQuery({
    queryKey: ['finance-refunds'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('financial_transactions')
        .select('amount')
        .eq('type', 'refund');
      if (error) throw error;
      return (data || []).reduce((s, r) => s + Number(r.amount), 0);
    },
    refetchInterval: 15000,
  }).data || 0;
  const totalRevenue = Math.max(0, grossRevenue - refundsTotal);
  const totalExpenses = expenses?.reduce((sum, exp) => sum + Number(exp.amount), 0) || 0;
  const pendingInvoices = invoices?.filter(inv => inv.status === 'pending').length || 0;
  const paidInvoices = invoices?.filter(inv => inv.status === 'paid').length || 0;
  const netProfit = totalRevenue - totalExpenses;

  return {
    totalRevenue,
    grossRevenue,
    refundsTotal,
    totalExpenses,
    netProfit,
    pendingInvoices,
    paidInvoices,
    totalOrders: validOrders.length,
    deliveredOrders: deliveredOrders.length,
    paidOrders: paidOrders.length,
    cancelledOrders: (orders?.length || 0) - validOrders.length,
  };
};
